export const GETPOKEMONDETAIL = "GETPOKEMONDETAIL";
export const GETPOKEMONQUERY = "GETPOKEMONQUERY";
export const FILTERPOKEMONS = "FILTERPOKEMONS";
export const GETPAGINATION = "GETPAGINATION";
export const GETPOKEMONS = "GETPOKEMONS";
export const GETTYPES = "GETTYPES";
export const START = "START";
export const ALL = "ALL";
